### ISSUE TITLE
Unit Testing with Linux agents are taking longer to complete

### ISSUE THREAD

**Issue by idaviddesmet** [idaviddesmet/NaCl.Core#29]
Testing should be taking around 2 minutes but is taking longer than usual on Linux.
I had the same issue with another project when running against SDK 2.2.300 as specified [here](https://github.com/dotnet/core/issues/2880) and [here](https://github.com/dotnet/core/issues/2775).

**GitHub Actions** CI result:

```bash
Test Run Successful.
Total tests: 121
     Passed: 121
 Total time: 7.7948 Minutes
```

**Azure DevOps** CI result:

```bash
Total tests: 121. Passed: 121. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 8.5036 Minutes
```

**AppVeyor** CI result (it took longer than it reports):

```bash
Test Run Successful.
Total tests: 121
     Passed: 121
 Total time: 2.2034 Minutes
```

**Comment by idaviddesmet** [comment]
Using the `UseDotNet@2` task and specifying SDK 2.2.301 but it keeps using `2.151.2` for running the tests... ¯\_(ツ)_/¯

**Comment by idaviddesmet** [comment]
Azure tasks have been updated; I've excluded Tests project from coverage.
Somehow, I'm not able to display the coverage results under the `Code Coverage` tab.
Tests running on Linux are still taking longer to complete.

**Comment by idaviddesmet** [comment]
`Code Coverage` tab fixed! Yey!!
The issue about tests taking longer to complete seems to be related to enabling coverage.

**Comment by daviddesmet** [comment]
Now the tests are taking longer with Windows agents.
