### ISSUE TITLE
Unsure about SnufflePoly1305 Decrypt

### ISSUE THREAD

**Issue by poettlr** [idaviddesmet/NaCl.Core#3]
Hello, 

I'm trying to use your code on small buffers for network encryption and the Decrypt function throws a [CryptographyException](https://github.com/idaviddesmet/NaCl.Core/blob/master/src/NaCl.Core/Base/SnufflePoly1305.cs#L100) "The ciphertext is too short." 

I compared it to other ChaCha20Poly1305 implementations and removed the `_snuffle.NonceSizeInBytes()`. I'm not even close to understanding the consequences but all your unit tests are still working as expected. 

Is it safe to use the code that way? 

Example: 

```
public struct KeepAlivePacket {
    public uint clientIndex;
    public uint maxClients;
}


//in unit test
var packet = new KeepAlivePacket {
    clientIndex = 0,
    maxClients = 6
};

byte[] key = ByteUtils.Generate256BitKey();
byte[] add = EncryptionHelper.CreateAdditionalData(...);
byte[] nonce = EncryptionHelper.CreateNonce(...);

var chacha = new ChaCha20Poly1305(key);

byte[] encrypted = chacha.Encrypt(packetBuffer, additionalData, nonce);
byte[] decrypted = chacha.Decrypt(encrypted, additionalData, nonce);
```

I'd love to get a reply, 
Cheers

**Comment by idaviddesmet** [comment]
Hello @poettlr,

Thanks for opening the issue. The exception you are getting is because the `nonce` is not taken into account when evaluating the ciphertext length in the decrypt method.

I've already fixed the issue which will be available in the next commit. 😉
