### ISSUE TITLE
Match signature of new Core APIs?

### ISSUE THREAD

**Issue by macaba** [idaviddesmet/NaCl.Core#32]
There is a new [System.Security.Cryptography.AesGcm API](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.aesgcm.encrypt?view=netstandard-2.1#System_Security_Cryptography_AesGcm_Encrypt_System_ReadOnlySpan_System_Byte__System_ReadOnlySpan_System_Byte__System_Span_System_Byte__System_Span_System_Byte__System_ReadOnlySpan_System_Byte__) in .NET Core, it might be beneficial to add the same method signatures into NaCl.Core.

Note: this new API seems to interop to native OS libraries, I'm intrigued to see how they compare against the intrinsic-optimised NaCl.Core, so I will probably try this at some point.

**Comment by idaviddesmet** [comment]
I don’t see any issue in adding support for the same method signatures; it could like side-by-side with the existing ones.

Regarding AesGsm, I was looking at it when it was first announced, it was considered in NaCl.Core but then dropped in favor of official CoreFX one. If I’m not mistaken, the code lives [here](https://github.com/dotnet/corefx/tree/master/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography) in case you wanna have a peek 😉

**Comment by idaviddesmet** [comment]
Just a head up. This will be addressed next, need to merge the changes with the new commits.
