### ISSUE TITLE
Replacing heap allocations by stack allocations

### ISSUE THREAD

**Issue by moien007** [idaviddesmet/NaCl.Core#40]
Hi,

The [`stackalloc`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/stackalloc) keyword and [`Span<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.span-1) type can eliminate a lot of allocations in the library and removing the need of types like [`Array8`](https://github.com/idaviddesmet/NaCl.Core/blob/master/src/NaCl.Core/Internal/Array8.cs) and [`Array16`](https://github.com/idaviddesmet/NaCl.Core/blob/master/src/NaCl.Core/Internal/Array16.cs).

**Comment by idaviddesmet** [comment]
Hello,

It wasn’t long ago when the library moved to using Span<T> type, by then it used extensively those two mentioned types. The library still has room for improvements, there was also a talk about using Intrinsics but unfortunately I’ve a deadline to meet at work and haven’t got time to look into it. Saying so, I wonder if you could help to the project by providing a PR for this issue. I will greatly appreciate it 🙂

**Comment by idaviddesmet** [comment]
@moien007 

I've been rewritten `ChaCha20` using your suggestion, replacing the struct types with [`stackalloc`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/stackalloc) keyword and [`Span<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.span-1) along with using [`System.Buffers.BinaryPrimitives`](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.binary.binaryprimitives) giving the below result:

```
// * Summary *


BenchmarkDotNet=v0.12.0, OS=Windows 10.0.19582

Intel Core i5-8265U CPU 1.60GHz (Whiskey Lake), 1 CPU, 8 logical and 4 physical cores

.NET Core SDK=3.1.101

  [Host] : .NET Core 3.1.1 (CoreCLR 4.700.19.60701, CoreFX 4.700.19.60801), X64 RyuJIT


|                           Method |     Mean |    Error |   StdDev | Rank |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|
---------------------------------- |---------:|---------:|---------:|-----:|-------:|------:|------:|----------:|
| ProcessKeyStreamBlockUsingStruct | 733.6 ns | 11.94 ns | 11.17 ns |    2 | 0.0553 |     - |     - |     176 B |
|   ProcessKeyStreamBlockUsingSpan | 590.5 ns | 11.82 ns | 17.69 ns |    1 | 0.0277 |     - |     - |      88 B |
```

**Comment by idaviddesmet** [comment]
The changes are now up at fd6ae392489cf26a5e965361241ac8591b6cb485.

**Comment by moien007** [comment]
> @moien007
> 
> I've been rewritten `ChaCha20` using your suggestion, replacing the struct types with [`stackalloc`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/stackalloc) keyword and [`Span<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.span-1) along with using [`BinaryPrimitives`](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.binary.binaryprimitives) giving the below result:
> 
> ```
> // * Summary *
> 
> 
> BenchmarkDotNet=v0.12.0, OS=Windows 10.0.19582
> 
> Intel Core i5-8265U CPU 1.60GHz (Whiskey Lake), 1 CPU, 8 logical and 4 physical cores
> 
> .NET Core SDK=3.1.101
> 
>   [Host] : .NET Core 3.1.1 (CoreCLR 4.700.19.60701, CoreFX 4.700.19.60801), X64 RyuJIT
> 
> 
> |                           Method |     Mean |    Error |   StdDev | Rank |  Gen 0 | Gen 1 | Gen 2 | Allocated |
> |
> ---------------------------------- |---------:|---------:|---------:|-----:|-------:|------:|------:|----------:|
> | ProcessKeyStreamBlockUsingStruct | 733.6 ns | 11.94 ns | 11.17 ns |    2 | 0.0553 |     - |     - |     176 B |
> |   ProcessKeyStreamBlockUsingSpan | 590.5 ns | 11.82 ns | 17.69 ns |    1 | 0.0277 |     - |     - |      88 B |
> ```
> 
> **Note:** This benchmark was run from LINQPad.

Great, heap allocations almost halved. Keep it up.
