### ISSUE TITLE
Binary endianness safety

### ISSUE THREAD

**Issue by moien007** [idaviddesmet/NaCl.Core#41]
Hi,

The class [`ByteIntegerConverter`](https://github.com/idaviddesmet/NaCl.Core/blob/master/src/NaCl.Core/Internal/ByteIntegerConverter.cs) have methods like `LoadLittleEndian32` and `StoreLittleEndian32` which is not checking for system endianness (which is not guaranteed to be little-endian in .NET). In the old .NET days, we were checking [`System.BitConverter.IsLittleEndian`](https://docs.microsoft.com/en-us/dotnet/api/system.bitconverter.islittleendian) field to finding out system endianness and reversing the bytes to achieve the endianness that we were looking for, but in this modern .NET age we should consider using [`System.Buffers.BinaryPrimitives`](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.binary.binaryprimitives) class (my benchmarks showed me it is significantly faster than bitwise operations like `<<`  and `||` since it takes advantage of CPU instructions like `rotl` and `rotr` on X86 machines).

**Comment by idaviddesmet** [comment]
Hello again 🙂

Seems you already made some local changes... would you kindly help the project with a PR of your changes? It will be a great addition to the library.

**Comment by moien007** [comment]
> Hello again 🙂
> 
> Seems you already made some local changes... would you kindly help the project with a PR of your changes? It will be a great addition to the library.

Sure, I will address #40 in my PR too.

**Comment by idaviddesmet** [comment]
> Sure, I will address #40 in my PR too.

Sounds great! Looking forward to it 🙂

**Comment by idaviddesmet** [comment]
Closed by fd6ae392489cf26a5e965361241ac8591b6cb485
