### ISSUE TITLE
.NET Standard and .NET Framework 4.5 Support

### ISSUE THREAD

**Issue by moien007** [idaviddesmet/NaCl.Core#6]

**Comment by idaviddesmet** [comment]
The library already supports .NET Standard, do you mean any specific version?

Regarding .NET 4.5, I see no issue in adding support for it for the library, the Benchmarks and Tests have to remain for now in .NET 4.7 due to broken dependencies.

**Comment by idaviddesmet** [comment]
I’ve added support for .NET Standard 1.3 and .NET Framework 4.5. The updated package will be available at NuGet soon.

**Comment by idaviddesmet** [comment]
Does the latest version meets your needs?

**Comment by moien007** [comment]
@idaviddesmet Yes, it does, thank you.
