### ISSUE TITLE
Does the MAC need a nonce?

### ISSUE THREAD

**Issue by macaba** [idaviddesmet/NaCl.Core#8]
When I read the authoritative source:
https://cr.yp.to/mac.html

It talks of a 16 byte nonce for Poly1305 MACs. 

Using the code below to generate MACs, where is the nonce involved? 

```
// Use the primitive to compute a tag
var tag = Poly1305.ComputeMac(key, data);

// ... or to verify a tag
Poly1305.VerifyMac(key, data, tag);
```

Thanks.

**Comment by idaviddesmet** [comment]
The Poly1305 (as mentioned in its class summary) one-time MAC is based on [RFC 8439](https://tools.ietf.org/html/rfc8439#section-2.5), quoting:

> Poly1305 is a one-time authenticator designed by D. J. Bernstein. Poly1305 takes a 32-byte one-time key and a message and produces a 16-byte tag.  This tag is used to authenticate the message.

> The original article ([Poly1305](https://tools.ietf.org/html/rfc8439#ref-Poly1305)) is titled "The Poly1305-AES message-authentication code", and the MAC function there requires a 128-bit AES key, a 128-bit "additional key", and a 128-bit (non-secret) nonce. AES is used there for encrypting the nonce, so as to get a unique (and secret) 128-bit string, but as the paper states, "There is nothing special about AES here.  One can replace AES with an arbitrary keyed function from an arbitrary set of nonces to 16-byte strings."

The mentioned RFC gives a more detailed explanation of the algorithm.
In summary, the inputs to Poly1305 RFC 8439 are:

- A 256-bit one-time key
- An arbitrary length message

This implementation is based on poly1305 implementation by [Andrew Moon](https://github.com/floodyberry/poly1305-donna).

I will update the README to make it clearer.

**Comment by macaba** [comment]
Thank you for the clarification - it wasn't clear to me immediately that it should be a _one-time_ use of the key. How is this intended to be used practically? It seems to be that both ends of a send-receive channel need to constantly synchronise one-time keys in order to verify MACs.

I'm coding a library for sending DTOs - it has two modes;
1. Sending messages in the clear but authenticated. (MAC)
2. Sending messages encrypted & authenticated. (AEAD)

Scenario 2 is easy enough - sender/receiver synchronise a pair of secret keys that don't change, 1 for each direction, using an out-of-band mechanism (HTTPS) and the nonce is a sequence. (ChaCha20Poly1305)
How do I solve Scenario 1 with the primitives in NaCl.Core?

**Comment by macaba** [comment]
I'm satisfied to use the framework HMAC256 function so this issue is pretty much closed. 👍
